services:
  web:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - .docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir:
      - /var/www/html
